GET http://localhost:4000/healthcheck


###
POST http://localhost:4000/people

{
    "customerName": "Foo",
    "contactName": "Bar",
    "country": "AUT",
    "hourlyRate": 42
}

###
GET http://localhost:4000/people/00000000-0000-0000-0000-000000000000

###
GET http://localhost:4000/people
