# @name customers
GET http://localhost:4000/customers

###

@customerID = {{customers.response.body.$[0].customerID}}

GET http://localhost:4000/customers/{{customerID}}

###
GET http://localhost:4000/customers/00000000-0000-0000-0000-000000000000

###
POST http://localhost:4000/customers

{
    "customerName": "Bcme Corp",
    "contactName": "Foo Bar",
    "country": "DEU",
    "hourlyRate": "42"
}

###
DELETE http://localhost:4000/customers/{{customerID}}

###
PATCH http://localhost:4000/customers/{{customerID}}

{
    "customerName": "Acme Corp Ltd."
}

###
GET http://localhost:4000/panic

###
GET http://localhost:4000/customers?orderBy=companyName
