FROM golang:latest AS builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -gcflags="-trimpath" -a -o ./server ./cmd/server

FROM alpine:latest
COPY --from=builder /app/server ./
RUN chmod +x ./server
CMD ["./server"]
