// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: greet/greet.proto

package greet

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_greet_greet_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings.
type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_greet_greet_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FromTo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   int32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *FromTo) Reset() {
	*x = FromTo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromTo) ProtoMessage() {}

func (x *FromTo) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromTo.ProtoReflect.Descriptor instead.
func (*FromTo) Descriptor() ([]byte, []int) {
	return file_greet_greet_proto_rawDescGZIP(), []int{2}
}

func (x *FromTo) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *FromTo) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

type NumericResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *NumericResult) Reset() {
	*x = NumericResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumericResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericResult) ProtoMessage() {}

func (x *NumericResult) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericResult.ProtoReflect.Descriptor instead.
func (*NumericResult) Descriptor() ([]byte, []int) {
	return file_greet_greet_proto_rawDescGZIP(), []int{3}
}

func (x *NumericResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type StepByStepResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*StepByStepResult_Result
	//	*StepByStepResult_Error
	Payload isStepByStepResult_Payload `protobuf_oneof:"payload"`
}

func (x *StepByStepResult) Reset() {
	*x = StepByStepResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepByStepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepByStepResult) ProtoMessage() {}

func (x *StepByStepResult) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepByStepResult.ProtoReflect.Descriptor instead.
func (*StepByStepResult) Descriptor() ([]byte, []int) {
	return file_greet_greet_proto_rawDescGZIP(), []int{4}
}

func (m *StepByStepResult) GetPayload() isStepByStepResult_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *StepByStepResult) GetResult() *NumericResult {
	if x, ok := x.GetPayload().(*StepByStepResult_Result); ok {
		return x.Result
	}
	return nil
}

func (x *StepByStepResult) GetError() *status.Status {
	if x, ok := x.GetPayload().(*StepByStepResult_Error); ok {
		return x.Error
	}
	return nil
}

type isStepByStepResult_Payload interface {
	isStepByStepResult_Payload()
}

type StepByStepResult_Result struct {
	Result *NumericResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type StepByStepResult_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StepByStepResult_Result) isStepByStepResult_Payload() {}

func (*StepByStepResult_Error) isStepByStepResult_Payload() {}

var File_greet_greet_proto protoreflect.FileDescriptor

var file_greet_greet_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x65, 0x6d, 0x6f, 0x1a, 0x1d, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0a,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x06, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0d, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x78, 0x0a, 0x10, 0x53,
	0x74, 0x65, 0x70, 0x42, 0x79, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2a,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x3b, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x12, 0x30, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x12, 0x2e, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x32, 0x83, 0x01, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x68, 0x47, 0x75, 0x72, 0x75, 0x12,
	0x33, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x12,
	0x0c, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x1a, 0x13, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x30, 0x01, 0x12, 0x42, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x69, 0x62, 0x6f, 0x6e,
	0x61, 0x63, 0x63, 0x69, 0x53, 0x74, 0x65, 0x70, 0x42, 0x79, 0x53, 0x74, 0x65, 0x70, 0x12, 0x0c,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x1a, 0x16, 0x2e, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x42, 0x79, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_greet_greet_proto_rawDescOnce sync.Once
	file_greet_greet_proto_rawDescData = file_greet_greet_proto_rawDesc
)

func file_greet_greet_proto_rawDescGZIP() []byte {
	file_greet_greet_proto_rawDescOnce.Do(func() {
		file_greet_greet_proto_rawDescData = protoimpl.X.CompressGZIP(file_greet_greet_proto_rawDescData)
	})
	return file_greet_greet_proto_rawDescData
}

var file_greet_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_greet_greet_proto_goTypes = []interface{}{
	(*HelloRequest)(nil),     // 0: demo.HelloRequest
	(*HelloReply)(nil),       // 1: demo.HelloReply
	(*FromTo)(nil),           // 2: demo.FromTo
	(*NumericResult)(nil),    // 3: demo.NumericResult
	(*StepByStepResult)(nil), // 4: demo.StepByStepResult
	(*status.Status)(nil),    // 5: google.rpc.Status
}
var file_greet_greet_proto_depIdxs = []int32{
	3, // 0: demo.StepByStepResult.result:type_name -> demo.NumericResult
	5, // 1: demo.StepByStepResult.error:type_name -> google.rpc.Status
	0, // 2: demo.Greeter.SayHello:input_type -> demo.HelloRequest
	2, // 3: demo.MathGuru.GetFibonacci:input_type -> demo.FromTo
	2, // 4: demo.MathGuru.GetFibonacciStepByStep:input_type -> demo.FromTo
	1, // 5: demo.Greeter.SayHello:output_type -> demo.HelloReply
	3, // 6: demo.MathGuru.GetFibonacci:output_type -> demo.NumericResult
	4, // 7: demo.MathGuru.GetFibonacciStepByStep:output_type -> demo.StepByStepResult
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_greet_greet_proto_init() }
func file_greet_greet_proto_init() {
	if File_greet_greet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_greet_greet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_greet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_greet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromTo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_greet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumericResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_greet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepByStepResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_greet_greet_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*StepByStepResult_Result)(nil),
		(*StepByStepResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_greet_greet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_greet_greet_proto_goTypes,
		DependencyIndexes: file_greet_greet_proto_depIdxs,
		MessageInfos:      file_greet_greet_proto_msgTypes,
	}.Build()
	File_greet_greet_proto = out.File
	file_greet_greet_proto_rawDesc = nil
	file_greet_greet_proto_goTypes = nil
	file_greet_greet_proto_depIdxs = nil
}
