// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package greet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/demo.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greet/greet.proto",
}

// MathGuruClient is the client API for MathGuru service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MathGuruClient interface {
	GetFibonacci(ctx context.Context, in *FromTo, opts ...grpc.CallOption) (MathGuru_GetFibonacciClient, error)
	GetFibonacciStepByStep(ctx context.Context, opts ...grpc.CallOption) (MathGuru_GetFibonacciStepByStepClient, error)
}

type mathGuruClient struct {
	cc grpc.ClientConnInterface
}

func NewMathGuruClient(cc grpc.ClientConnInterface) MathGuruClient {
	return &mathGuruClient{cc}
}

func (c *mathGuruClient) GetFibonacci(ctx context.Context, in *FromTo, opts ...grpc.CallOption) (MathGuru_GetFibonacciClient, error) {
	stream, err := c.cc.NewStream(ctx, &MathGuru_ServiceDesc.Streams[0], "/demo.MathGuru/GetFibonacci", opts...)
	if err != nil {
		return nil, err
	}
	x := &mathGuruGetFibonacciClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MathGuru_GetFibonacciClient interface {
	Recv() (*NumericResult, error)
	grpc.ClientStream
}

type mathGuruGetFibonacciClient struct {
	grpc.ClientStream
}

func (x *mathGuruGetFibonacciClient) Recv() (*NumericResult, error) {
	m := new(NumericResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mathGuruClient) GetFibonacciStepByStep(ctx context.Context, opts ...grpc.CallOption) (MathGuru_GetFibonacciStepByStepClient, error) {
	stream, err := c.cc.NewStream(ctx, &MathGuru_ServiceDesc.Streams[1], "/demo.MathGuru/GetFibonacciStepByStep", opts...)
	if err != nil {
		return nil, err
	}
	x := &mathGuruGetFibonacciStepByStepClient{stream}
	return x, nil
}

type MathGuru_GetFibonacciStepByStepClient interface {
	Send(*FromTo) error
	Recv() (*StepByStepResult, error)
	grpc.ClientStream
}

type mathGuruGetFibonacciStepByStepClient struct {
	grpc.ClientStream
}

func (x *mathGuruGetFibonacciStepByStepClient) Send(m *FromTo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mathGuruGetFibonacciStepByStepClient) Recv() (*StepByStepResult, error) {
	m := new(StepByStepResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MathGuruServer is the server API for MathGuru service.
// All implementations must embed UnimplementedMathGuruServer
// for forward compatibility
type MathGuruServer interface {
	GetFibonacci(*FromTo, MathGuru_GetFibonacciServer) error
	GetFibonacciStepByStep(MathGuru_GetFibonacciStepByStepServer) error
	mustEmbedUnimplementedMathGuruServer()
}

// UnimplementedMathGuruServer must be embedded to have forward compatible implementations.
type UnimplementedMathGuruServer struct {
}

func (UnimplementedMathGuruServer) GetFibonacci(*FromTo, MathGuru_GetFibonacciServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFibonacci not implemented")
}
func (UnimplementedMathGuruServer) GetFibonacciStepByStep(MathGuru_GetFibonacciStepByStepServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFibonacciStepByStep not implemented")
}
func (UnimplementedMathGuruServer) mustEmbedUnimplementedMathGuruServer() {}

// UnsafeMathGuruServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MathGuruServer will
// result in compilation errors.
type UnsafeMathGuruServer interface {
	mustEmbedUnimplementedMathGuruServer()
}

func RegisterMathGuruServer(s grpc.ServiceRegistrar, srv MathGuruServer) {
	s.RegisterService(&MathGuru_ServiceDesc, srv)
}

func _MathGuru_GetFibonacci_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FromTo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MathGuruServer).GetFibonacci(m, &mathGuruGetFibonacciServer{stream})
}

type MathGuru_GetFibonacciServer interface {
	Send(*NumericResult) error
	grpc.ServerStream
}

type mathGuruGetFibonacciServer struct {
	grpc.ServerStream
}

func (x *mathGuruGetFibonacciServer) Send(m *NumericResult) error {
	return x.ServerStream.SendMsg(m)
}

func _MathGuru_GetFibonacciStepByStep_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MathGuruServer).GetFibonacciStepByStep(&mathGuruGetFibonacciStepByStepServer{stream})
}

type MathGuru_GetFibonacciStepByStepServer interface {
	Send(*StepByStepResult) error
	Recv() (*FromTo, error)
	grpc.ServerStream
}

type mathGuruGetFibonacciStepByStepServer struct {
	grpc.ServerStream
}

func (x *mathGuruGetFibonacciStepByStepServer) Send(m *StepByStepResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mathGuruGetFibonacciStepByStepServer) Recv() (*FromTo, error) {
	m := new(FromTo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MathGuru_ServiceDesc is the grpc.ServiceDesc for MathGuru service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MathGuru_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.MathGuru",
	HandlerType: (*MathGuruServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFibonacci",
			Handler:       _MathGuru_GetFibonacci_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFibonacciStepByStep",
			Handler:       _MathGuru_GetFibonacciStepByStep_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "greet/greet.proto",
}
